# Generated by Django 3.2.9 on 2022-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
            ],
        ),
    ]
